In [1]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([ 1.12605181,  0.62072945,  2.14814308,  0.32089815,  1.96565104,
        1.0304299 , -0.84886443,  0.30477772,  0.73791721,  1.34512397])

In [9]:
B = np.random.randn(10)

In [10]:
B

array([-0.05991051,  1.49950061,  0.17403248, -0.21128663,  0.91359674,
        0.51249731, -0.21025035, -2.01006225, -0.11749652, -2.40957633])

In [11]:
np.add(A,B)

array([ 1.06614131,  2.12023006,  2.32217556,  0.10961152,  2.87924779,
        1.5429272 , -1.05911478, -1.70528454,  0.62042068, -1.06445236])

In [12]:
np.maximum(A,B)

array([ 1.12605181,  1.49950061,  2.14814308,  0.32089815,  1.96565104,
        1.0304299 , -0.21025035,  0.30477772,  0.73791721,  1.34512397])