In [1]:
import numpy as np
import pandas as pd 
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [13]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [14]:
pd.concat([ser1,ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [15]:
pd.concat([ser1,ser2], axis=1, keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [16]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [17]:
dframe1

X         Y         Z
0 -0.323633 -0.725754  0.447834
1  0.420424 -0.497617 -0.357092
2 -0.738353 -1.136002  0.374836
3 -1.064076 -0.107599 -0.848719

In [19]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [20]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.323633 -0.725754  0.447834
1       NaN  0.420424 -0.497617 -0.357092
2       NaN -0.738353 -1.136002  0.374836
3       NaN -1.064076 -0.107599 -0.848719
0  1.629784  0.755574  1.143059       NaN
1  2.035353 -2.351027  0.242554       NaN
2  0.677300  0.869452 -0.652765       NaN

In [21]:
pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.323633 -0.725754  0.447834
1       NaN  0.420424 -0.497617 -0.357092
2       NaN -0.738353 -1.136002  0.374836
3       NaN -1.064076 -0.107599 -0.848719
4  1.629784  0.755574  1.143059       NaN
5  2.035353 -2.351027  0.242554       NaN
6  0.677300  0.869452 -0.652765       NaN