In [44]:
import numpy as np

In [45]:
my_list1 = [1,2,3,4]

In [46]:
my_array1 = np.array(my_list1)

In [47]:
my_array1

array([1, 2, 3, 4])

In [48]:
my_list2= [11,22,33,44]

In [49]:
my_lists = [my_list1, my_list2]

In [50]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [51]:
my_array2 = np.array(my_lists)

In [52]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [53]:
my_array2.shape

(2, 4)

In [54]:
my_array2.dtype

dtype('int64')

In [71]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [56]:
my_zeros = np.zeros(5)

In [57]:
my_zeros.dtype

dtype('float64')

In [58]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [59]:
np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [60]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [79]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [84]:
arr1 = np.arange(0,6)

In [88]:
arr1 * arr1

array([ 0,  1,  4,  9, 16, 25])

In [89]:
arr1 / arr1

/home/user/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.])

In [92]:
arr2 = arr1[0:4].copy()

In [93]:
arr2

array([0, 1, 2, 3])

In [101]:
arr3 = [arr1, arr1*2]

In [103]:
arr3 = np.array(arr3)

In [104]:
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10]])

In [118]:
arr3 = np.arange(12).reshape((3,3))

ValueError: total size of new array must be unchanged

In [120]:
arr4 = np.arange(12).reshape((3,4))

In [121]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.exp(arr4)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
          1.09663316e+03],
       [  2.98095799e+03,   8.10308393e+03,   2.20264658e+04,
          5.98741417e+04]])

In [123]:
arr4 + arr4

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])